# Generated by Django 4.2.17 on 2025-01-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="姓名")),
                ("phone", models.CharField(max_length=20, verbose_name="电话")),
                ("email", models.EmailField(max_length=254, verbose_name="邮箱")),
                ("service", models.CharField(max_length=50, verbose_name="咨询类型")),
                ("message", models.TextField(verbose_name="咨询内容")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="提交时间"),
                ),
            ],
            options={
                "verbose_name": "联系咨询",
                "verbose_name_plural": "联系咨询",
                "ordering": ["-created_at"],
            },
        ),
    ]
