# Generated by Django 4.2.17 on 2025-01-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactmessage",
            name="service",
            field=models.CharField(
                choices=[
                    ("legal_consultation", "法律咨询"),
                    ("labor_compliance", "劳资合规"),
                    ("contract_optimization", "合约优化"),
                    ("debt_management", "债权管理"),
                    ("intellectual_property", "知识产权"),
                    ("corporate_governance", "公司治理"),
                ],
                max_length=50,
                verbose_name="咨询类型",
            ),
        ),
    ]
