# Generated by Django 4.2.17 on 2025-01-13 07:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_newscategory_news"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="分类名称")),
                ("slug", models.SlugField(unique=True, verbose_name="分类标识")),
                ("description", models.TextField(blank=True, verbose_name="分类描述")),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "文章分类",
                "verbose_name_plural": "文章分类",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Lawyer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="姓名")),
                ("title", models.CharField(max_length=100, verbose_name="职位")),
                ("image", models.ImageField(upload_to="lawyers/", verbose_name="照片")),
                ("introduction", models.TextField(verbose_name="简介")),
                ("email", models.EmailField(max_length=254, verbose_name="邮箱")),
                ("phone", models.CharField(max_length=20, verbose_name="电话")),
                (
                    "expertise_areas",
                    models.JSONField(default=list, verbose_name="专业领域"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "律师",
                "verbose_name_plural": "律师团队",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                ("slug", models.SlugField(unique=True, verbose_name="文章标识")),
                ("summary", models.TextField(verbose_name="摘要")),
                (
                    "content",
                    django_ckeditor_5.fields.CKEditor5Field(verbose_name="内容"),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        upload_to="articles/thumbnails/", verbose_name="缩略图"
                    ),
                ),
                ("views", models.IntegerField(default=0, verbose_name="浏览量")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="是否推荐"),
                ),
                (
                    "publish_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="发布时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.category",
                        verbose_name="分类",
                    ),
                ),
            ],
            options={
                "verbose_name": "文章",
                "verbose_name_plural": "文章",
                "ordering": ["-publish_date"],
            },
        ),
    ]
