# Generated by Django 4.2.17 on 2025-01-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_category_lawyer_article"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="客户姓名")),
                ("title", models.CharField(max_length=100, verbose_name="职位")),
                ("company", models.CharField(max_length=100, verbose_name="公司")),
                ("content", models.TextField(verbose_name="评价内容")),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "1星"),
                            (2, "2星"),
                            (3, "3星"),
                            (4, "4星"),
                            (5, "5星"),
                        ],
                        default=5,
                        verbose_name="评分",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="testimonials/",
                        verbose_name="头像",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否显示"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "客户评价",
                "verbose_name_plural": "客户评价",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
