# Generated by Django 4.2.17 on 2025-01-13 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_enterpriseservicepackage_enterpriseservicetype_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enterpriseserviceitem",
            name="type",
        ),
        migrations.DeleteModel(
            name="EnterpriseServicePackage",
        ),
        migrations.AlterUniqueTogether(
            name="enterpriseservicevalue",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="enterpriseservicevalue",
            name="service_item",
        ),
        migrations.DeleteModel(
            name="FamilyServicePackage",
        ),
        migrations.DeleteModel(
            name="EnterpriseServiceItem",
        ),
        migrations.DeleteModel(
            name="EnterpriseServiceType",
        ),
        migrations.DeleteModel(
            name="EnterpriseServiceValue",
        ),
    ]
