# Generated by Django 4.2.17 on 2025-01-13 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_remove_enterpriseserviceitem_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnterpriseServicePackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("standard", "标准版"),
                            ("premium", "高级版"),
                            ("deluxe", "豪华版"),
                        ],
                        max_length=20,
                        verbose_name="套餐类型",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="价格"
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "企业服务套餐",
                "verbose_name_plural": "企业服务套餐",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EnterpriseServiceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="服务类型")),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "企业服务类型",
                "verbose_name_plural": "企业服务类型",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="FamilyServicePackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="服务内容")),
                ("description", models.TextField(verbose_name="服务说明")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="价格"
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "家庭服务套餐",
                "verbose_name_plural": "家庭服务套餐",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EnterpriseServiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="服务标题")),
                ("content", models.TextField(verbose_name="服务内容")),
                ("description", models.TextField(verbose_name="服务说明")),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.enterpriseservicetype",
                        verbose_name="服务类型",
                    ),
                ),
            ],
            options={
                "verbose_name": "企业服务项目",
                "verbose_name_plural": "企业服务项目",
                "ordering": ["type__order", "order"],
            },
        ),
        migrations.CreateModel(
            name="EnterpriseServiceValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "package_type",
                    models.CharField(
                        choices=[
                            ("standard", "标准版"),
                            ("premium", "高级版"),
                            ("deluxe", "豪华版"),
                        ],
                        max_length=20,
                        verbose_name="套餐类型",
                    ),
                ),
                ("value", models.CharField(max_length=100, verbose_name="服务内容")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "service_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.enterpriseserviceitem",
                        verbose_name="服务项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "企业套餐服务内容",
                "verbose_name_plural": "企业套餐服务内容",
                "unique_together": {("service_item", "package_type")},
            },
        ),
    ]
