# Generated by Django 4.2.17 on 2025-01-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_enterpriseservicepackage_enterpriseservicetype_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="enterpriseserviceitem",
            options={
                "ordering": ["type__order", "order", "-created_at"],
                "verbose_name": "服务内容",
                "verbose_name_plural": "服务内容",
            },
        ),
        migrations.AlterModelOptions(
            name="enterpriseservicepackage",
            options={
                "ordering": ["order", "-created_at"],
                "verbose_name": "服务套餐",
                "verbose_name_plural": "服务套餐",
            },
        ),
        migrations.AlterModelOptions(
            name="enterpriseservicetype",
            options={
                "ordering": ["order", "-created_at"],
                "verbose_name": "服务类型",
                "verbose_name_plural": "服务类型",
            },
        ),
        migrations.RemoveField(
            model_name="enterpriseserviceitem",
            name="content",
        ),
        migrations.AddField(
            model_name="enterpriseserviceitem",
            name="supported_packages",
            field=models.ManyToManyField(
                to="app.enterpriseservicepackage", verbose_name="支持的套餐"
            ),
        ),
        migrations.AlterField(
            model_name="enterpriseserviceitem",
            name="title",
            field=models.CharField(max_length=200, verbose_name="服务内容"),
        ),
        migrations.AlterField(
            model_name="enterpriseservicepackage",
            name="type",
            field=models.CharField(
                choices=[
                    ("standard", "标准版"),
                    ("premium", "高级版"),
                    ("deluxe", "豪华版"),
                ],
                max_length=20,
                unique=True,
                verbose_name="套餐类型",
            ),
        ),
        migrations.AlterField(
            model_name="enterpriseservicetype",
            name="name",
            field=models.CharField(max_length=100, verbose_name="类型名称"),
        ),
    ]
