# Generated by Django 4.2.17 on 2025-01-13 09:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_alter_enterpriseserviceitem_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="familyservicepackage",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "家庭服务套餐",
                "verbose_name_plural": "家庭服务套餐",
            },
        ),
        migrations.RemoveField(
            model_name="familyservicepackage",
            name="order",
        ),
        migrations.AddField(
            model_name="familyservicepackage",
            name="service_type",
            field=models.CharField(
                default=django.utils.timezone.now,
                max_length=100,
                verbose_name="服务类型",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="EnterpriseServiceValue",
        ),
    ]
